### ISSUE TITLE
Application not running

### ISSUE THREAD

**Issue by gaurav6041** [kartikey54/VaccineAvailabilityNotifier#10]
Hi, Firstly would like to thank you for making this application.
Great initiative!!!!

My application is not coming up.

Below are the logs printed

```
npm WARN cowincheck@1.0.0 No repository field.

audited 180 packages in 2.409s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

-bash: pm2: command not found
```

Below are the versions
**node : v14.16.1**
**npm :6.14.12**
**os: macOS**

**Comment by csagar131** [comment]
hey @gaurav6041  kindy install pm2 using npm install -g pm2
