### ISSUE TITLE
Does this means it is working?

### ISSUE THREAD

**Issue by dhyani15** [kartikey54/VaccineAvailabilityNotifier#14]
Following the steps in the readme I am getting the final output in my terminal as
`
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │`
`│ 0  │ vaccineNotifier    │ fork     │ 0    │ online    │ 0%       │ 95.6mb   │`

**Comment by kartikey54** [comment]
Yes

**Comment by dhyani15** [comment]
Thanks for your prompt reply @kartikey54 But I am not getting an email for a pincode where the dashboard is showing availability. Can you please clarify when I generate the app password, apart from the .env file do I have to add it in my mail for Mac desktop app as well?
