### ISSUE TITLE
How to enable gmail acess to the app

### ISSUE THREAD

**Issue by deepakk7195** [kartikey54/VaccineAvailabilityNotifier#17]
Hi I am not able to find App Passwords under Signing in to Google, because there isn't any. The only section under this head is 'Password' which lets one to change the gmail password. So where to find the App Passwords?

**Comment by dhyani15** [comment]
It is probably because you haven't setup a 2 factor authentication.

> Under "Signing in to Google," select App Passwords. You may need to sign in. If you don’t have this option, it might be because:
> 2-Step Verification is not set up for your account.
> 2-Step Verification is only set up for security keys.
> Your account is through work, school, or other organization.
> You turned on Advanced Protection.
