### ISSUE TITLE
issue while following step 3 : command not found: pm2

### ISSUE THREAD

**Issue by SurendraKMali** [kartikey54/VaccineAvailabilityNotifier#37]
Step 1 and Step 2 done.

While following step 3  run: `npm i && pm2 start vaccineNotifier.js`
getting below error 

`command not found: pm2` 

![image](https://user-images.githubusercontent.com/37996959/116855447-0307cc00-ac17-11eb-9f6d-42a20fc35fe2.png)

**Comment by Pratik2125** [comment]
install pm2

**Comment by SurendraKMali** [comment]
@Pratik2125  : Yes sorted 
`npm i -g pm2`
