### ISSUE TITLE
pm2 is not a valid command

### ISSUE THREAD

**Issue by ketanbijwe** [kartikey54/VaccineAvailabilityNotifier#47]
zsh: command not found: pm2

![Screenshot 2021-05-03 at 11 26 18 PM](https://user-images.githubusercontent.com/31929352/116913358-0165f480-ac67-11eb-8618-10e4a349750e.png)

After changing pm2 to npm start, getting below error - 

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'start',
0 verbose cli   'vaccineNotifier.js'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/ketan/Downloads/VaccineAvailabilityNotifier-main/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/ketan/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 64eb22e72c8b5a5f
20 timing npm:load Completed in 18ms
21 timing command:run-script Completed in 2ms
22 timing command:start Completed in 13ms
23 verbose stack Error: missing script: start
23 verbose stack     at runScript (/usr/local/lib/node_modules/npm/lib/run-script.js:53:11)
24 verbose cwd /Users/ketan/Downloads/VaccineAvailabilityNotifier-main
25 verbose Darwin 20.3.0
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "vaccineNotifier.js"
27 verbose node v15.2.1
28 verbose npm  v7.0.8
29 error missing script: start
30 verbose exit 1

**Comment by AbhinavS96** [comment]
Try running sudo npm install pm2 -g

**Comment by ketanbijwe** [comment]
thanks
