### ISSUE TITLE
False Mail

### ISSUE THREAD

**Issue by jarvishu** [kartikey54/VaccineAvailabilityNotifier#52]
Hi All 
I am getting false email . 
The mail says that 1 slot is available but when I check the cowin website it isn't.
Sharing screenshot of both: 
Anyone else facing same issue ?
![image](https://user-images.githubusercontent.com/29713514/116960338-bb884b00-acbd-11eb-84c4-f41d381f7d5e.png)
![image](https://user-images.githubusercontent.com/29713514/116960370-ce028480-acbd-11eb-9592-d5ed0c685ec8.png)

**Comment by sid8840** [comment]
the script checks the slot in 1 min's time and sends the mail.
so it is possible that someone else books the slot in between.
I try to avoid those 1 capacity slots because of unavailability.
the script is working fine. 

> Hi All
> I am getting false email .
> The mail says that 1 slot is available but when I check the cowin website it isn't.
> Sharing screenshot of both:
> Anyone else facing same issue ?
> ![image](https://user-images.githubusercontent.com/29713514/116960338-bb884b00-acbd-11eb-84c4-f41d381f7d5e.png)
> ![image](https://user-images.githubusercontent.com/29713514/116960370-ce028480-acbd-11eb-9592-d5ed0c685ec8.png)

**Comment by manuagrwl** [comment]
to avoid this single slot menace, I changed "slot.available_capacity > 20" in the function "getSlotsForDate" in vaccineNotifier.js
