### ISSUE TITLE
Add .env to gitignore file

### ISSUE THREAD

**Issue by sohamsshah** [kartikey54/VaccineAvailabilityNotifier#54]
Adding .env to production isn't a good practice. Would like to RAISE a PR for the same.

P.S. - Loved your project :)

**Comment by shantnu-agarwal** [comment]
The purpose of the env in this project is to enable people to configure their own email, age, pincode, etc. Adding the ENV to gitignore would defeat the purpose of making this project accessible to a large set of people who wouldn't know how to set up a env file on their own. 

As per me, this is a non-issue.

**Comment by sohamsshah** [comment]
Fine, makes sense. Though, I suppose this is being used by developers; so a good readme with details for .env would do the purpose. Anyways, no problem. 

P.S. - In open source, never thumbs down someone's comment. Respect opinions to make it a positive place to work at. Thanks
