### ISSUE TITLE
How to check if it has been set up successully?

### ISSUE THREAD

**Issue by mansayyy** [kartikey54/VaccineAvailabilityNotifier#56]

**Comment by sid8840** [comment]
if you are getting mail..its ok

**Comment by mansayyy** [comment]
I dint receive any mail till now

**Comment by sid8840** [comment]
is pin code showing slots available on cowin site?

**Comment by mansayyy** [comment]
Nope, acha so it will mail only when it is available?

**Comment by sid8840** [comment]
> Nope, acha so it will mail only when it is available?

there you are!!

**Comment by mansayyy** [comment]
Haha, thanks !

**Comment by nomulas** [comment]
I thought there will be an initial email that will be sent when we start the application. So we will know the email notification are working.

**Comment by mansayyy** [comment]
Yeah even I thought so

**Comment by sid8840** [comment]
> I thought there will be an initial email that will be sent when we start the application. So we will know the email notification are working.

You can Check for serviceable pin code too.
