### ISSUE TITLE
The term 'pm2' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by csagar131** [kartikey54/VaccineAvailabilityNotifier#6]
while running the command : npm i && pm2 start vaccineNotifier.js  its showing the following error:
pm2: The term 'pm2' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by LalitKushwah** [comment]
Check once to install pm2 globally for example
npm install -g pm2

**Comment by kartikey54** [comment]
Closing this issue as @LalitKushwah resolved this.

**Comment by kamalkantnawal** [comment]
Just after installing pm2 globally if it still not working then, Define in System Env variables
**C:\Users\USERNAME\AppData\Roaming\npm**

After adding the path and a restart the application.
