### ISSUE TITLE
API showing 400 bad request when using this application or postman

### ISSUE THREAD

**Issue by Divyansh12** [kartikey54/VaccineAvailabilityNotifier#69]
API is showing 400 Bad Request when using with postman or with this application since today (It was working fine till yesterday night). But it is working when using the link in browser directly.

I have tried modifying the user-agent but still it is not working. 

Can anyone help me with this issue ?

![image](https://user-images.githubusercontent.com/31319271/117276883-f2f12600-ae7c-11eb-9b66-14bcc793c324.png)

**Comment by TitusRobyK** [comment]
Set a user-agent in header , while using POSTMAN , you will get the response..
Similarly headers in vaccine-notifier.js has to updated for this application to work
