### ISSUE TITLE
An End-to-End application would be great.

### ISSUE THREAD

**Issue by snehitvaddi** [kartikey54/VaccineAvailabilityNotifier#73]
Giving code may be useful only for developers/geeks.
Having an End-to-End application will serve all kinds of people.

If anyone has developed an End-to-End application, please share it here.

**Comment by tejas-2232** [comment]
Yeah. This is a great idea.
Need to think about the process of making it.
If anyone is doing so I would more than happy to help 💯

**Comment by shadabshaikh0** [comment]
@snehitvaddi @tejas-2232  Please go through #61

**Comment by tejas-2232** [comment]
> @snehitvaddi @tejas-2232 Please go through #61

thanks, man for redirecting. 
simple and short messages like this help alot.

**Comment by snehitvaddi** [comment]
Yup, this discussion makes sence🙏

**Comment by pranshukas** [comment]
> Yeah. This is a great idea.
> Need to think about the process of making it.
> If anyone is doing so I would more than happy to help 💯

I want some help @tejas-2232 Please Help me out. I am working on making Frontend Webapp on which users can directly put their emails and pin code and it will send the data processing in the background, but facing some problems. 
Please Help Me out !!
